### ISSUE TITLE
getmail-gmail-xoauth-tokens socket.gaierror

### ISSUE THREAD

**Issue by alpe12** [getmail6/getmail6#113]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/local/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/getmail-gmail-xoauth-tokens", line 122, in <module>
    sys.stdout.write("%s" % auth.token())
  File "/usr/local/bin/getmail-gmail-xoauth-tokens", line 100, in token
    self.refresh_tokens()
  File "/usr/local/bin/getmail-gmail-xoauth-tokens", line 95, in refresh_tokens
    d = self.get_response(self.data['token_uri'], params)
  File "/usr/local/bin/getmail-gmail-xoauth-tokens", line 68, in get_response
    response = urllibrequest.urlopen(url, encoded).read()
  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Try again>
```

**Comment by rpuntaie** [comment]
I tried this

https://github.com/getmail6/getmail6/blob/master/docs/getmailrc-examples#:~:text=use_xoauth2

I have no problems.

A nuisance is that I have to repeat the `--init` step after some time.

**Comment by alpe12** [comment]
It fixed itself after some time.
I too have to use --init from time to time. No fix for this?
