### ISSUE TITLE
No token is generated for O365

### ISSUE THREAD

**Issue by rhadw** [getmail6/getmail6#159]
Hi.
As per the readme file, I've tried to generate tokens for an O365 account by I always end up with the following error:

`Traceback (most recent call last):
  File "/usr/local/bin/getmail-gmail-xoauth-tokens", line 155, in <module>
    oauthd.handle_request()
  File "/usr/lib/python3.8/socketserver.py", line 294, in handle_request
    ready = selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/getmail-gmail-xoauth-tokens", line 163, in <module>
    code = query_string["code"][0]
KeyError: 'code'
`
I've read the documentation over and over but no luck...
Can anyone point me in the right direction?

**Comment by rhadw** [comment]
Well, seems like I was stupid. I needed to copy the whole URL in order to get the token.
I was only copying the code...
Sorry!
