### ISSUE TITLE
getmail-gmail-xoauth-tokens no longer working after fix for #178

### ISSUE THREAD

**Issue by dvlohp** [getmail6/getmail6#196]
Unfortunately, I can no longer refresh my gmail auth tokens with getmail-gmail-xoauth-tokens from the current release

The error is
```
$ ./getmail-gmail-xoauth-tokens --init myInitFile
Visit this url to obtain a verification code:
Traceback (most recent call last):
  File "getmail-gmail-xoauth-tokens", line 157, in <module>
    print("    %s\n" % auth.code_url(args.port))
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "getmail-gmail-xoauth-tokens", line 86, in code_url
    params = self.copy('scope', 'client_id', 'redirect_uri')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "getmail-gmail-xoauth-tokens", line 75, in copy
    data[k] = self.data[k]
              ~~~~~~~~~^^^
KeyError: 'redirect_uri'
```

I bisected the issue and it was introduced by 
```
commit 1c186ff0fbbdd65a778dbcd243e2027d8cb7d17d
Author: Jérôme Pouiller <jerome.pouiller@silabs.com>
Date:   Mon Jan 8 13:18:19 2024 +0100

    Allow to customize 'redirect_uri'
```
which fixed issue #178 .

This change is in 6.18.14 and later.

It seems that the copy() method does not handle missing keys gracefully.

**Comment by rpuntaie** [comment]
Would you fix it and create a pull request?

**Comment by rpuntaie** [comment]
Maybe you can check that the fix works for you.

**Comment by dvlohp** [comment]
Works! +1: 

Thanks a billion! :smiley:
