### ISSUE TITLE
setup.py install  --show-default-install-dirs TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by jidanni** [getmail6/getmail6#26]
OK, let's try #25, even with "install",
```
$ python3 setup.py install  --show-default-install-dirs
Default installation directories:
  scripts :        /usr/bin
Traceback (most recent call last):
  File "setup.py", line 51, in <module>
    print('  Python modules : %s' % os.path.join(distutils.sysconfig.get_config_var('LIBP'), 'site-packages'))
  File "/usr/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Probably not ready for python3.

**Comment by rpuntaie** [comment]
This is wrong usage.
By the fix of #25, this is also solved.
